### ISSUE TITLE
Received this email from Travis but not sure what to do with this?

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-dataset#260]
I received the following email from Travis for the conp-dataset repo:

![Screen Shot 2020-04-15 at 11 28 56 AM](https://user-images.githubusercontent.com/1402456/79355997-663f9700-7f0c-11ea-85e4-1904eeea7070.png)

Links from the picture:
- [Build #576 is still failing](https://travis-ci.org/github/CONP-PCNO/conp-dataset/builds/675330177?utm_medium=notification&utm_source=email)
- [95bd1a7 CHANGESET -->](https://github.com/CONP-PCNO/conp-dataset/compare/6ffda37b6a81...95bd1a720eee)

Note: the PR it refers to was passing travis before the merge.

**Comment by mathdugre** [comment]
@cmadjar, this issue arises since the test for authenticated datasets are currently skipped on PR for security reasons, however, they are not on the master branch of the repository (see _Handling authentication_ in #197). Due to missing configuration on the repo, the build is failing.

#252 is trying to address this issue for dataset from Zenodo

**Comment by glatard** [comment]
Closing this now, feel free to reopen @cmadjar
