### ISSUE TITLE
Utility and future of DATS.json-ld

### ISSUE THREAD

**Issue by emmetaobrien** [CONP-PCNO/conp-dataset#272]
One of the proposed purposes of having `DATS.json-ld` files was to provide schema.org-compatible information to allow CONP datasets to be indexed by Google, if I understand correctly, and that objective is now elegantly handled by https://github.com/CONP-PCNO/conp-portal/pull/195.

The current set of `DATS.json-ld` files is partial and they are incomplete because of updates to our `DATS.json` format, and before I dive into updating them and generating` DATS.json-ld` for newer datasets, I wanted to confirm what purpose they are now envisioned as serving and how we intend them to function.  Linking controlled vocabularies to fields, for example, is a function that needs to be done manually, and almost certainly best done by the laboratory generating the data.  I would suggest that when we develop a GUI for submitters to generate `DATS.json` files, we might provide options for them to attach that sort of data and generate a `DATS.json-ld` file as well.  However, our existing datasets do not in general have that sort of data attached, and even the most basic functionality there would be complex to automate if possible (for example, JSON-LD annotations for a `creators `field need to differ depending on whether the entries are individuals or institutions and it is not straightforward to automatically distinguish between those cases, so that needs manual intervention.)

**Comment by zxenia** [comment]
My thoughts on this topic:
I think we definitely need to do more mapping from DATS to schema.org and/or PROV ontology, maybe some other schema. Mapping all fields would allow us to produce richer RDF data for all datasets - we can try to dump it in a triple store or in Nexus. We will need to generate stable URIs for each dataset.
The very valuable part of such an RDF graph would be ontology and controlled vocabularies terms that are used for metadata. They are common nodes shared among the datasets. But, as @emmetaobrien said it is a manual task to annotate the dataset with ontologies. A possible way to encourage the use of ontologies and CV is to provide auto-complete from an external API in a future GUI for DATS creation (e.g. ontology lookup service https://www.ebi.ac.uk/ols/index) so that the label and URI are fetched and saved respectively in DATS file.

I have done some mapping from DATS to PROV Ontology a while ago by providing context to PROV and generating RDF, here is an [example how the context and final RDF looks like ](https://github.com/zxenia/dataset_to_prov).

And below is an example of how the DATS uses ontologies and datasets can be linked via the common ontology.
```
"isAbout":[
   {
      "@type":"MolecularEntity",
      "name":"total RNA",
      "characteristics":[
         {
            "@type":"Material",
            "name":"Brodmann (1909) area 11",
            "identifier":{
               "identifier":"UBERON:0013528",
               "identifierSource":"http://purl.obolibrary.org/obo/UBERON_0013528"
            },
            "derivesFrom":[
               {
                  "@type":"Material",
                  "name":"brain",
                  "identifier":{
                     "identifier":"UBERON:0000955",
                     "identifierSource":"http://purl.obolibrary.org/obo/UBERON_0000955"
                  }
               }
            ]
         }
      ]
   }
]
```

DATS `"isAbout"` can be mapped to  `"sdo:about"` and so on. So when we generate RDF Molecular entity is a valid RDF entity. If several datasets are about the same "MolecularEntity" they are linked via its URI.

**Comment by cmadjar** [comment]
Discussed at the CONP dev meeting of June 3rd, 2020:
- Starting with putting the schema.org info from DATS
- Link with the GUI in the future https://github.com/CONP-PCNO/conp-portal/issues/301
- json-ld : will allow ingestion by Nexus

**Comment by cmadjar** [comment]
@emmetaobrien is the current CONP DATS schema in the schema.org format?

Timeline for this: end of August

**Comment by xlecours** [comment]
The code to generate a schema.org schema is at https://github.com/CONP-PCNO/conp-portal/blob/master/app/search/models.py#L332. I think this property of  DATSDataset objects is never called.

**Comment by zxenia** [comment]
To add a bit more context: currently, only properties required by [CONP DATS](https://github.com/CONP-PCNO/schema/blob/master/dataset_schema.json) ([ "title", "types", "creators", "licenses", "description", "keywords", "version" ]) are used to generate json-ld for Google dataset search.

**Comment by cmadjar** [comment]
@emmetaobrien @zxenia can this be closed?

**Comment by cmadjar** [comment]
@emmetaobrien @zxenia can this be closed?

**Comment by emmetaobrien** [comment]
I think @zxenia's code for annotating terms answers the question I opened this issue to address.
