### ISSUE TITLE
Tag Zenodo/OSF users in the PR about their dataset

### ISSUE THREAD

**Issue by glatard** [CONP-PCNO/conp-dataset#277]
## Purpose

Notify the user who uploaded a dataset to Zenodo or OSF that their dataset is being processed.

## Context

Give users news about their dataset.

## Possible Implementation (optional)

Tag users in the PR, which requires getting the user email or GH account from Zenodo or OSF.

@joeyzhou98

**Comment by cmadjar** [comment]
As much as this is a really good idea, I don't think this is feasible as neither Zenodo nor OSF show user's contact information in their API responses (I really took a deep look into the responses and cannot find any information).

I will close this issue since I do not see a way we could implement this. @glatard feel free to reopen if you think of a way to do that.
