### ISSUE TITLE
BigBrain_3DSurfaces doesn't have a valid DATS file

### ISSUE THREAD

**Issue by glatard** [CONP-PCNO/conp-dataset#339]
* Test build: 
https://app.circleci.com/pipelines/github/CONP-PCNO/conp-dataset/362/workflows/dc192141-f465-44c5-ae2d-179bd34bbb5b/jobs/703/parallel-runs/0?filterBy=FAILED

* Standard error:
```
________ TestDataset.test_has_valid_dats[projects/BigBrain_3DSurfaces] _________
 
Dataset projects/BigBrain_3DSurfaces doesn't contain a valid DATS.json.
 
------------------------------ Captured log call -------------------------------
 
ERROR    scripts.dats_validator.validator:validator.py:48 1 Validation error in extraProperties.5.values.0: Additional properties are not allowed ('parent_dataset_id' was unexpected)
 
_
```

* Help requested from:
@emmetaobrien  (this is related to #338)

**Comment by zxenia** [comment]
Setting ` additionalProperties` to True entails that anything can be added there.

**Comment by emmetaobrien** [comment]
This morning I have been looking into this, and I think it is better for me to change the format of the existing entries to something` annotation_schema` does support rather than relax a constraint that would then have to apply to all the other places we use `annotation_schema` (which is a lot of places) and risk errors slipping through, so am doing that now; expect a PR correcting the three invalid DATS files imminently.

**Comment by glatard** [comment]
I agree completely @emmetaobrien, allowing for extra properties is a bit brittle to typos and other errors.

**Comment by emmetaobrien** [comment]
Yes, I will document the change in the PR and let @liamocn know.

**Comment by cmadjar** [comment]
That dataset is now passing CircleCI so closing the issue

**Comment by glatard** [comment]
thank you so much for fixing this @emmetaobrien
