### ISSUE TITLE
preventad-open-bids fails to download

### ISSUE THREAD

**Issue by glatard** [CONP-PCNO/conp-dataset#340]
* Test build: 
https://app.circleci.com/pipelines/github/CONP-PCNO/conp-dataset/362/workflows/dc192141-f465-44c5-ae2d-179bd34bbb5b/jobs/703/parallel-runs/0?filterBy=FAILED

* Standard error:
```
________ TestDataset.test_has_valid_dats[projects/preventad-open-bids] _________
 
Dataset projects/preventad-open-bids doesn't contain a valid DATS.json.
 
------------------------------ Captured log call -------------------------------
 
ERROR    scripts.dats_validator.validator:validator.py:48 1 Validation error in extraProperties.6.values.0: Additional properties are not allowed ('parent_dataset_id' was unexpected)
 
_
```

* Help requested from:
@cmadjar @emmetaobrien 
Related issue: #338

**Comment by cmadjar** [comment]
looks like the DATS error is not present anymore in circle CI. There is still the dataset timed out issue though.

@glatard should we close this one and open another one for preventad-open-bids with the timeout issue?

**Comment by glatard** [comment]
I think we could just leave this one open and track the download error here.

**Comment by glatard** [comment]
The download error is coming from the download test of files in the parent dataset (submodule), in spite of the parent dataset passing the tests. This is most likely because the parent dataset needs different credentials than the dataset, and CircleCI uses the same set of credentials for both.

I see two possible solutions:
1. We don't test submodules at all: if the submodule is in CONP, great, it's tested somewhere else; otherwise, too bad, but this is also not a CONP dataset so it's not in our scope.
2. We extend the tests to support different credentials for the dataset and subdatasets.

I'm leaning slightly toward solution 1, as it is way simpler than 2, and 2 is also a rabbit hole. Thoughts @emmetaobrien and @cmadjar?

**Comment by cmadjar** [comment]
@glatard in theory, the credentials are identical for those two datasets since they are connecting to the same LORIS instance.

However, I agree with you and lean towards solution 1 too. Seems redundant to test a submodule that we already test elsewhere and there is nothing we can do if a submodule is not a CONP dataset.

**Comment by emmetaobrien** [comment]
Option 1 seems reasonable to me too.

**Comment by glatard** [comment]
great, I'll change that soon. @mathdugre had told me that testing submodules was going to create issues, I should have listened to him :)

**Comment by cmadjar** [comment]
@glatard did you update the LORIS credentials for the tests of this dataset in the end?

Latest error is:
```
The dataset timed out after 120 seconds before retrieving a file. Cannot to tell if the download would be sucessful.
BIDS_dataset/sub-3360165/ses-NAPFU36/sub-3360165_ses-NAPFU36_scans.json has size of inf Bytes.
```

from https://app.circleci.com/pipelines/github/CONP-PCNO/conp-dataset/754/workflows/5b3eab59-7971-4100-81c8-67e4ef4d28e5/jobs/1518

**Comment by cmadjar** [comment]
For some reason, the URLs of every scans.json file are pointing to all the scans.json files... 

```
(datalad_python3) ses-NAPEN00 $ git annex whereis sub-3017785_ses-NAPEN00_scans.json 
whereis sub-3017785_ses-NAPEN00_scans.json (3 copies) 
  	c1310042-0393-48a1-9b0f-886f0353c93d -- cecile@cecile-dev.loris.ca:/data/CONP/preventad-open-bids
   	c6a15a49-4e7f-4cf7-8d63-7b70b5376bb0 -- cecile@cecile-dev.loris.ca:/data/CONP/preventad-open-bids
   	cf13d535-b47c-5df6-8590-0793cb08a90a -- [datalad]

  datalad: https://openpreventad.loris.ca/api/v0.0.3-dev//candidates/1000173/NAPBL00/bidsfiles/sub-1000173_ses-NAPBL00_scans.json
  datalad: https://openpreventad.loris.ca/api/v0.0.3-dev//candidates/1000173/NAPEN00/bidsfiles/sub-1000173_ses-NAPEN00_scans.json
  datalad: https://openpreventad.loris.ca/api/v0.0.3-dev//candidates/1000173/NAPFU03/bidsfiles/sub-1000173_ses-NAPFU03_scans.json
  datalad: https://openpreventad.loris.ca/api/v0.0.3-dev//candidates/1000173/NAPFU12/bidsfiles/sub-1000173_ses-NAPFU12_scans.json
  datalad: https://openpreventad.loris.ca/api/v0.0.3-dev//candidates/1004359/PREBL00/bidsfiles/sub-1004359_ses-PREBL00_scans.json
  datalad: https://openpreventad.loris.ca/api/v0.0.3-dev//candidates/1004359/PREFU12/bidsfiles/sub-1004359_ses-PREFU12_scans.json
...
```

Need to find out why and fix this...

**Comment by cmadjar** [comment]
After discussions with Yarik on issue https://github.com/datalad/datalad/issues/5429, the reason multiple URLs are appended to the `*scans.json` and `*bval` files is related to all the files having the same hash as they are identical.

Since those files do not contain any sensitive data (just protocol descriptions), instead of annexing those files, they will be tracked by git directly.

Datasets affected:
- preventad-registered (BIDS subdataset)
- preventad-open-bids

@glatard there is one thing that is still a mystery: the CircleCI timeout message from the tests when they try to download the `*scans.json` files. According to Yarik, there is no reason the amount of stored URLs should affect the download time of those files. See https://github.com/datalad/datalad/issues/5429#issuecomment-783482145

**Comment by glatard** [comment]
Hi @cmadjar, preventad-open-bids seems to be passing now, can we close this?

**Comment by cmadjar** [comment]
Good catch! Thank you. It is indeed fixed now
