### ISSUE TITLE
Create a separate block of code to do validation of extraProperties that have been created for CONP

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-dataset#345]
There appears to be no check on whether the CONP_status field is valid or not. Valid options for that field are: `conp`, `canadian`, `external`

A check should be added to the tests so that we ensure that proper values are set for the field.

**Comment by emmetaobrien** [comment]
Looking at the existing DATS.json files I see "CONP" is capitalised.

**Comment by cmadjar** [comment]
Right. That is very possible. I was looking at the CONP portal code to figure out what the values should be but it modifies everything to lower case before checking if the value is correct.

Very possible that the values should be `CONP`, `Canadian` and `External` then. Can you confirm?

**Comment by zxenia** [comment]
This feature would be a part of custom validation.

**Comment by emmetaobrien** [comment]
"external" is currently all lower-case.

**Comment by cmadjar** [comment]
Updated the title of the ticket as all extraProperties should be checked by the validator, not just the conp_status. 

for conp_status: valid values are `CONP`, `Canadian` and `external`

**Comment by glatard** [comment]
@zxenia why can't this be part of the validation against our custom schema?

**Comment by zxenia** [comment]
Hi @glatard ! As I see it we cannot change our custom schema to require `extraProperties` to contain categories `subjects`, `files ` and `CONP_status ` because those categories are only required on dataset_schema level. The `extraProperties` is defined by category_values_pair_schema.json schema and used not only on dataset_schema level but in other subschemas, being basically a schema for any kind of extra information. So we cannot just add files and subjects as required fields in category_values_pair_schema.json because once `extraProperties` is used anywhere else it will require this to be filled.
Plus category_values_pair_schema.json is nicely modeled in a way that we can add any property category there and its value. So what we have to do is just to check that certain category that we require is there and not empty.

**Comment by cmadjar** [comment]
@zxenia I believe this is done and can be closed, right? Let me know. Thanks!

**Comment by zxenia** [comment]
@cmadjar yes, it's done and merged to master!

**Comment by cmadjar** [comment]
Thank you! That's what I thought but wanted to double check before closing the issue.
