### ISSUE TITLE
multicenter-phantom

### ISSUE THREAD

**Issue by glatard** [CONP-PCNO/conp-dataset#410]
* Test build: 
https://app.circleci.com/pipelines/github/CONP-PCNO/conp-dataset/999/workflows/fada49c9-234b-43a3-9cad-663941ed875a/jobs/2008/parallel-runs/1

* Standard error:
```
___________ TestDataset.test_download[projects/multicenter-phantom] ____________
The dataset timed out after 120 seconds before retrieving a file. Cannot to tell if the download would be sucessful.
phantom_963271_SLH_SCAN2_20140320_fieldmapBOLD_005.mnc has size of inf Bytes.
----------------------------- Captured stdout call -----------------------------
projects/multicenter-phantom/phantom_963271_SLH_SCAN2_20140320_fieldmapBOLD_005.mnc
```
This is most likely an authentication error. I had updated the credentials a few days ago and it seemed to worked fine. I have a feeling that LORIS periodically reset the password of the account used in the tests.

* Help requested from:
@glatard @cmadjar

**Comment by cmadjar** [comment]
@joeyzhou98 indeed, the passwords reset every 6 months. Not sure which account is used for the phantom dataset though. @glatard was it your credentials?

**Comment by glatard** [comment]
yes, my credentials are used. Would it be possible to extend their lifetime?

**Comment by cmadjar** [comment]
@glatard I just checked and your password should expire on 2021-02-26. Did you already reset the password on 2020-08-26 by any chance? Just checking...

FYI - I changed the expiry to be a year from now (2021-09-11) for your accounts on both the phantom and the open PREVENT-AD instances. This way, you'll have to update the password for Circle CI only once a year :).

**Comment by cmadjar** [comment]
This could be due to the fact that one of the URLs annexed for the file still refers to phantom-dev... Will create a script to easily remove old invalid URLs from the datalad remote to avoid those issues with other datasets as well.
Because the URL is embedded within the datalad remote, we cannot use the uuid to delete the useless old URLs... A script needs to be created to find out the URL to remove and run git annex rmurl.

```
git annex whereis <file> --json
git annex rmurl <file> <url>
```

This is for example an issue for the recrawled BigBrain datasets where it still tries to download at the old FTP location: https://github.com/CONP-PCNO/conp-portal/issues/408.

**Comment by cmadjar** [comment]
Removing the bad URLs phantom-dev.loris.ca appears to have solved the recurrent issue for this dataset. :-)
