### ISSUE TITLE
Polygenic Risk Score dataset(s)

### ISSUE THREAD

**Issue by emmetaobrien** [CONP-PCNO/conp-dataset#432]
An initial dataset of output data and summary documents was posted to Zenodo at https://zenodo.org/record/4042021 yesterday, with manually generated DATS.json; this did not get picked up by the Zenodo crawler and we are currently looking into why.

**Comment by cmadjar** [comment]
The crawler currently crashes on this dataset due to the fact that the crawler expects a `conceptdoi` field associated to the dataset, however, a `conceptdoi` is attributed to a dataset only if there are no existing `doi` specified when uploading the data. Basically,
- if a user does not specify a DOI at the time of upload, Zenodo will create a Concept DOI and another DOI for the version of the dataset. The Concept DOI represents the dataset and all its versions.
- if a user specifies a DOI at the time of the upload, Zenodo will not create DOIs (neither concept DOI or version DOI).  

@emmetaobrien **The fact that the DOI is not a Zenodo DOI means that the files in those datasets cannot be edited** So if the DATS.json or README files need to be updated for those datasets, it cannot be done, or at least easily...
See first general question from https://help.zenodo.org/.

I will send a PR to modify the crawler code to take the DOI instead of the concept DOI when no concept DOI is available for the crawled dataset.

**Comment by cmadjar** [comment]
The PR above should fix the crawler. Once this is merged, I will pull the code on the crawler server and that dataset should be caught by the crawlers then.

**Comment by cmadjar** [comment]
https://github.com/CONP-PCNO/conp-dataset/pull/435 has been merged and the dataset now appears on the portal
