### ISSUE TITLE
Calgary Campinas Public Brain MR Dataset

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-dataset#443]
## Purpose

More information about the dataset can be found: https://sites.google.com/view/calgary-campinas-dataset/home

Procedure sent to Patrick on how to integrate this dataset on the portal:
There are 3 possibilities to add a dataset to CONP:
1. upload via Zenodo and use the tag 'canadian-open-neuroscience-platform'
2. upload via OSD and use the tag `canadian-open-neuroscience-platform`
3. upload via DataLad

The three possibilities are documented in https://portal.conp.ca/share

**Comment by emmetaobrien** [comment]
Update on meeting I have just had with Patrick and Roberto Medeiros de Souza at Calgary concerning this dataset:

- Dataset contains 359 subjects in NIfTI and 167 raw datasets in HDF5 (non-overlapping)
- Updated roughly every 6 months, next update due in December (modest due to COVID-19)
- About 500 GB of data currently, expected to possibly grow to ~ 1.5 TB (or considerably if adding processed derivatives) by the end of 2021
- Data currently stored on OneDrive (link has to be renewed every 7 days), AWS, Google Drive (regularly temporarily blocked because of too much traffic).
- This might be a good candidate/test case for hosting data locally.

**Comment by emmetaobrien** [comment]
The plan for this dataset is now to proceed with loading it onto a local server, as discussed in the comment on https://github.com/CONP-PCNO/conp-portal/issues/302 concerning the meeting of October 19 2020; it is anticipated that this server will bceome available this week.

**Comment by emmetaobrien** [comment]
This dataset is now loaded into CONP, as of https://github.com/CONP-PCNO/conp-dataset/pull/479.
