### ISSUE TITLE
Datasets don't pass tests

### ISSUE THREAD

**Issue by glatard** [CONP-PCNO/conp-dataset#67]
Continuous testing of datasets is now in place, see https://travis-ci.org/CONP-PCNO/conp-dataset However, no dataset currently passes the tests. We need to fix it or the tests are essentially useless. 

## Expected Behavior

All the datasets in this repo should pass the tests.

## Current Behavior

All the datasets are currently failing the tests.

## Possible fix (optional)

This should probably be assigned to multiple people.

**Comment by gi114** [comment]
Hi @glatard 

Luckily the issue seems to be very straightforward and valid for all datasets tested here: They all miss a dats.json file at the root directory. This is because we only recently formulated this requirement and it has not yet been implemented in any of the datasets. The first example in the pipeline I believe is in PR for the visual-working-memory dataset.

This is the PR: https://github.com/conpdatasets/visual-working-memory/pull/2
You can validate the dats.json in the dats-descriptor branch using the following perl link: https://github.com/conpdatasets/1000GenomesProject/blob/44a7ee921ec5e1ced3991fab443d50f5af94d2bb/scripts/1000genomes_validate_json.pl before approving

Once this PR is approved, we should expect see the visual-working-memory dataset passing

**Comment by glatard** [comment]
Hi @gi114, checking the presence of dats.json is the first step in the tests, but the next ones might also fail. A more complete checklist is here: https://github.com/CONP-PCNO/conp-dataset/blob/master/.github/PULL_REQUEST_TEMPLATE.md You should run the tests locally to make sure that everything passes.

**Comment by gi114** [comment]
Hi Tristan,

Perfect, thanks for sharing!

Best
Giulia

Il giorno sab 3 ago 2019 alle ore 09:29 Tristan Glatard <
notifications@github.com> ha scritto:

**Comment by gi114** [comment]
Hi,

I spotted another problem related to the visual-working-memory dataset which has a file called README but not a README.md and the tests do not recognize it..that caused the test to fail locally even if a DATS.json file is present at the root. If both these requirements are met, the tests pass for this dataset though.

Will tests be accepting README as well as a change? otherwise I will specify README.md by updating the current PR. I can see that some datasets do not have a README file at all.

**Comment by gi114** [comment]
Hi,

For the moment this is a li[localTestsResults.txt](https://github.com/CONP-PCNO/conp-dataset/files/3483408/localTestsResults.txt)st of issue for each of the datasets in project.

[localTestsResults.txt](https://github.com/CONP-PCNO/conp-dataset/files/3483409/localTestsResults.txt)

**Comment by glatard** [comment]
I think enforcing README.md is good, so that README files display well on GitHub.

**Comment by gi114** [comment]
Hi @glatard, sure! I will update the current PR for the visual-working-memory repo so that README.md is enforced.
