### ISSUE TITLE
Clarify Zenodo upload requirements in the docs

### ISSUE THREAD

**Issue by surchs** [CONP-PCNO/conp-dataset#680]
A user who is going to host their data on Zenodo and wants CONP to know about it is going to follow our documentation.

Currently we are advising to enter meta-data on the Zenodo portal and add a tag of `canadian-open-neuroscience-platform` so the crawler can find it. 
In addition to what the crawler gets, we also need manually annotated meta-data to generate a valid DATS.json file, e.g.
- the "community" the data is from (canadian, international, internal)
- the number of subjects in the dataset

This means that a user following our current docs will need to be contacted again and asked to update the incomplete DATS.json file generated by the crawler with these meta-data and then manually upload.

An alternative would be to ask the user to annotate the meta-data first on the CONP DATS editor, download the generated DATS file, include it in the submission, and then enter the appropriate meta-data information again on the Zenodo side. The downside of this is probably that a user might be less willing to do the annotation work twice and only upload on Zenodo. 

Things to do:
- [ ] discuss the path we suggest the user takes to get their meta-data ingested in CONP
- [ ] clarify our expectations in the docs
- [ ] publish the docs on the CONP portal

**Comment by cmadjar** [comment]
@surchs thank you for creating the issue. In the latest documentation (see PR https://github.com/CONP-PCNO/conp-documentation/pull/76) where the instructions for upload are a little bit different:

We now clearly state that the dataset requires a DATS.json and README.md file at the root of the datasets (with instructions on how to create the DATS file). This will avoid the need of back and forth with the user because the crawler did not populate all the fields since the DATS file would be created and uploaded at the first upload of the user.

With this new set of instructions, it might resolve the issue we had with the Douglas dataset.

**Comment by cmadjar** [comment]
PR with the updated documentation was merged and the new instructions are now on the portal
